wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u" -O "IPV6-1.m3u"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV-tvbox.txt" -O "IPV6-1.txt"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/fenxp/iptv/main/live/ipv6.m3u" -O "IPV6-2.m3u"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/fenxp/iptv/main/live/ipv6.txt" -O "IPV6-2.txt"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/drangjchen/IPTV/main/M3U/ipv6.m3u" -O "IPV6-3.m3u"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/BurningC4/Chinese-IPTV/master/TV-IPV4.m3u" -O "IPV6-4.m3u"
