wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/ngo5/IPTV/main/m3u/ipv6Plus.m3u" -O "IPV6-Plus.m3u"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u" -O "IPV6.m3u"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/fenxp/iptv/main/live/ipv6.m3u" -O "IPV6-1.m3u"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/drangjchen/IPTV/main/M3U/ipv6.m3u" -O "IPV6-2.m3u"
wget "https://mirror.ghproxy.com/https://raw.githubusercontent.com/BurningC4/Chinese-IPTV/master/TV-IPV4.m3u" -O "IPV6-3.m3u"
